Add support for CHM
sindresorhus/file-type pull request #424
Opened 2020-12-18 11:04 UTC by Richienb

> [**Microsoft Compiled HTML Help**](https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help) is a Microsoft proprietary online help format, consisting of a collection of HTML pages, an index and other navigation tools. 

Filename extension: `chm`
Media type: [`application/vnd.ms-htmlhelp`](https://www.iana.org/assignments/media-types/application/vnd.ms-htmlhelp)

The magic number is the text [`ITSF`](https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help#File_format) in ASCII.

Fixes: #422

2020-12-18 11:17 UTC, sindresorhus approved these changes

2020-12-19 19:14 UTC, Borewit requested changes

2020-12-19 19:14 UTC, Borewit commented on core.js
> +	if (checkString('ITSF')) {
Please move this up to the 4-byte signatures, to prevent unnecessary data to be read.

2020-12-20 15:07 UTC, Borewit approved these changes
LGTM

2020-12-21 10:04 UTC, merged