add support for fbx
sindresorhus/file-type pull request #605
Opened 2023-08-07 14:37 UTC by anatawa12

If you're adding support for a new file type, please follow the below steps:

I could not find any good mime type so I use new mime type instead.

The most popular documentation about fbx: https://code.blender.org/2013/08/fbx-binary-file-format-specification/

- **One PR per file type.**
- Add a fixture file named `fixture.<extension>` to the `fixture` directory.
- Add the file extension to the `extensions` array in `supported.js`.
- Add the file's MIME type to the `types` array in `supported.js`.
- Add the file type detection logic to the `core.js` file
- Respect the sequence:
	- Signature with shorter sample size (counted from offset 0 until the last required byte position) will be executed first.
	- Only the initial determination for the file type counts for the sequence.
	- Existing signatures requiring same sample length (same *signature group*) will be tested prior to your new detections. Yours will be last. (rational: common formats first).
- Add the file extension to the `FileType` type in `core.d.ts`.
- Add the file's MIME type to the `MimeType` type in `core.d.ts`.
- Add the file extension to the `Supported file types` section of the readme in alphabetical order, in the format ```- [`<extension>`](URL) - Format name```, for example, ```- [`png`](https://en.wikipedia.org/wiki/Portable_Network_Graphics) - Portable Network Graphics```
- Add the file extension to the `keywords` array in the `package.json` file.
- Run `$ npm test` to ensure the tests pass.
- Open a pull request with a title like `Add support for Format`, for example, `Add support for PNG`.
- The pull request description should include a link to the official page of the file format or some other source. Also include a link to where you found the file type detection / magic bytes and the MIME type.

2023-08-07 14:40 UTC, anatawa12 commented
I fogot to add fbx file

2023-08-07 16:21 UTC, sindresorhus requested changes

2023-08-07 16:22 UTC, sindresorhus commented
> Open a pull request with a title like Add support for Format, for example, Add support for PNG.

2023-08-07 18:28 UTC, anatawa12 commented on readme.md
> +- [`fbx`](https://en.wikipedia.org/wiki/FBX) - A model format used by many creation application invented by Autodesk
Should I add more information or should I make simpler?

2023-11-01 07:22 UTC, Borewit commented on readme.md
> +- [`fbx`](https://en.wikipedia.org/wiki/FBX) - A model format used by many creation application invented by Autodesk
```suggestion
- [`fbx`](https://en.wikipedia.org/wiki/FBX) - FBX (Filmbox) is a proprietary file format (.fbx) developed by Kaydara and owned by [Autodesk](https://en.wikipedia.org/wiki/Autodesk). It is used to provide interoperability between digital content creation applications.
```

2023-11-01 07:23 UTC, Borewit commented on readme.md
> +- [`fbx`](https://en.wikipedia.org/wiki/FBX) - A model format used by many creation application invented by Autodesk
Suggestion: https://github.com/sindresorhus/file-type/pull/605#discussion_r1378468646

2023-11-01 10:50 UTC, anatawa12 commented on readme.md
> +- [`fbx`](https://en.wikipedia.org/wiki/FBX) - A model format used by many creation application invented by Autodesk
Thank you for suggestion! I've committed your suggestion

2023-11-10 19:32 UTC, merged