Use `@file-type/xml` as a detector example
sindresorhus/file-type pull request #708
Opened 2024-12-19 18:09 UTC by Borewit

Adds the following to README:
- Refer to `@file-type/xml` for XML based formats
- Use `@file-type/xml` to demonstrate adding a custom detector

2025-02-22 09:16 UTC, sindresorhus commented on readme.md
> +```
Wrong place. This should not be before the description of custom detectors. It should probably be after the `### Example writing a custom detector` section. Same in index.d.ts

2025-02-22 11:09 UTC, Borewit commented on readme.md
> +```
The example I added is to show how to add an existing available (plugin) detector to file-type.
I intentionally placed that **before** the section in which we explaining how to implement your own detector.

2025-02-22 11:22 UTC, sindresorhus commented on readme.md
> +```
Makes sense, but should at minimum be after `- Modifying the detection behavior of existing `FileTypeResult` types.`

2025-02-22 19:06 UTC, Borewit commented on readme.md
> +```
Changed quite a bit in the flow, aiming for make it more readable. Also give a better structure to allow other possible future file-type extensions.

2025-02-23 11:07 UTC, sindresorhus commented on core.d.ts
> +2. **Tokenizer Interaction**: If the detector modifies the tokenizers position (`tokenizer.position` is advanced), no further detectors are executed. In this case, the file type remains `undefined`,
`tokenizer's` was correct

2025-02-23 11:08 UTC, sindresorhus commented on readme.md
> +- `.svg` - Supported by [third party detector](#available-third-party-file-type-detectors).
```suggestion
- `.svg` - Supported by [third-party detector](#available-third-party-file-type-detectors).
```

2025-02-23 11:16 UTC, sindresorhus requested changes

2025-02-23 11:16 UTC, sindresorhus commented on readme.md
> +Detectors can be added via the constructor options or by modifying FileTypeParser#detectors directly.
```suggestion
Detectors can be added via the constructor options or by modifying `FileTypeParser#detectors` directly.
```

2025-02-23 19:57 UTC, merged