Add support for POTX
sindresorhus/file-type pull request #710
Opened 2024-12-24 15:20 UTC by sly7-7

Related to #709, if it's ok for you, fit with the guidelines, and you want, I will make other PRs for the other extensions.

2024-12-26 21:03 UTC, Borewit requested changes

2024-12-26 21:03 UTC, Borewit commented on readme.md
> +- [`potx`](https://en.wikipedia.org/wiki/List_of_Microsoft_Office_filename_extensions) - Microsoft Powerpoint template
```suggestion
- [`potx`](https://en.wikipedia.org/wiki/List_of_Microsoft_Office_filename_extensions) - Microsoft PowerPoint template
```

2024-12-26 21:03 UTC, Borewit commented
Thanks for your contribution @sly7-7, your code is looking good. 
Please use the initial comment for the PR description.

2024-12-26 21:07 UTC, sly7-7 commented
Thanks for your feedback, I will do the changes tomorrow, I'm away from keyword right now.

2024-12-27 09:58 UTC, Borewit approved these changes
LGTM

2024-12-27 10:00 UTC, merged